import Header from "@/components/header/header";
import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
// import "./globals.css";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["200", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <body className={robotoMono.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
